---

- name: Playing with Ansible & Git
  connection: local
  gather_facts: false
  hosts: localhost

  # These variables are needed to bootstrap Ansible
  vars:
    ansible_sudo_password: '{{ lookup("env", "SUDO_PASSWORD") }}'
  tasks:
    - name: Parsing .env file into local playbook variable for Python script
      command: cat {{ playbook_dir }}/../.env
      register: ENV
    - debug: var=ENV.stdout
    - name: Run Py script
      script: '{{ playbook_dir }}/../hello_world_reader_app.py'
      environment: "{{ ENV }}"
      register: LOGGING
      become: no
      run_once: true
    - debug: var=LOGGING.stdout
